# I. $LU$ factorization of a square matrix

Consider a simple naive implementation of the LU decomposition. 

Note that we're using the `numpy` arrays to represent matrices [do **not** use `np.matrix`].

In [1]:
import numpy as np

def diy_lu(a):
    """Construct the LU decomposition of the input matrix.
    
    Naive LU decomposition: work column by column, accumulate elementary triangular matrices.
    No pivoting.
    """
    N = a.shape[0]
    
    u = a.copy()    #   u is a copy of given matrix
    L = np.eye(N)   #   L is an eye matrix
    for j in range(N-1):
        lam = np.eye(N) #   lam is the same as N
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u

        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u

In [15]:
# Now, generate a full rank matrix and test the naive implementation

import numpy as np

N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)

np.linalg.matrix_rank(a)

6

In [3]:
# Tweak the printing of floating-point numbers, for clarity
np.set_printoptions(precision=3)

In [4]:
a = np.random.randint(0, 10, (4, 4))
a

array([[9, 2, 1, 0],
       [0, 2, 9, 5],
       [3, 9, 6, 6],
       [3, 2, 3, 5]])

In [17]:
print(a1)
L, u, permutation_matrix = diy_lu_piv(a1)

print(a1, "\n")
print(L, "\n")
print(u, "\n")
print(permutation_matrix, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print(L@u@permutation_matrix - a1)
print(L@u - a1)

[[3.    3.    3.    3.    3.    3.   ]
 [3.    3.    1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]]
Iteration number 0: 

[[ 3.     3.     3.     3.     3.     3.   ]
 [ 0.     0.    -1.636 -1.929 -2.118 -2.25 ]
 [ 0.    -1.636 -2.118 -2.348 -2.483 -2.571]
 [ 0.    -1.929 -2.348 -2.531 -2.634 -2.7  ]
 [ 0.    -2.118 -2.483 -2.634 -2.717 -2.769]
 [ 0.    -2.25  -2.571 -2.7   -2.769 -2.812]]
Iteration number 1: 

[[ 3.     3.     3.     3.     3.     3.   ]
 [ 0.     0.    -1.636 -1.929 -2.118 -2.25 ]
 [   nan    nan   -inf   -inf   -inf   -inf]
 [   nan    nan   -inf   -inf   -inf   -inf]
 [   nan    nan   -inf   -inf   -inf   -inf]
 [   nan    nan   -inf   -inf   -inf   -inf]]
Iteration number 2: 

[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan 

# II. The need for pivoting

Let's tweak the matrix a little bit, we only change a single element:

In [16]:
a1 = a.copy()
a1[1, 1] = 3

Resulting matix still has full rank, but the naive LU routine breaks down.

In [7]:
np.linalg.matrix_rank(a1)

4

In [8]:
l, u = diy_lu(a1)

print(l, u)

[[1.    0.    0.    0.   ]
 [0.    1.    0.    0.   ]
 [0.333 2.778 1.    0.   ]
 [0.333 0.444 0.069 1.   ]] [[  9.      2.      1.      0.   ]
 [  0.      3.      9.      5.   ]
 [  0.      0.    -19.333  -7.889]
 [  0.      0.      0.      3.322]]


### Test II.1

For a naive LU decomposition to work, all leading minors of a matrix should be non-zero. Check if this requirement is satisfied for the two matrices `a` and `a1`.

(20% of the grade)

In [9]:
def single_minor(matrix, i, j):
    return np.linalg.det(np.delete(np.delete(matrix, i, axis=0), j, axis=1))

def check_LU_cond(matrix):
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[0]):
            if (single_minor(matrix, i, j) == 0):
                return False
    return True

print('Check for a matrix: {}'.format(check_LU_cond(a)))
print('Check for a1 matrix: {}'.format(check_LU_cond(a1)))

Check for a matrix: True
Check for a1 matrix: True


### Test II.2

Modify the `diy_lu` routine to implement column pivoting. Keep track of pivots, you can either construct a permutation matrix, or a swap array (your choice).

(40% of the grade)

Implement a function to reconstruct the original matrix from a decompositon. Test your routines on the matrices `a` and `a1`.

(40% of the grade)

In [10]:
def swap_lines(a, permutation_matrix, index_0)
    max_index = a[0, j:].max_index().shape[-1]
    temporary_matrix = np.eye(a.size[0])
    temporary_matrix[j, j] = 0
    temporary_matrix[max_index, max_index] = 0
    temporary_matrix[j, max_index] = 1
    temporary_matrix[max_index, j] = 1

SyntaxError: invalid syntax (<ipython-input-10-71da81a3afd7>, line 1)

In [13]:
def diy_lu_piv(a):
    """Construct the LU decomposition of the input matrix.
    
    Naive LU decomposition: work column by column, accumulate elementary triangular matrices.
    No pivoting.
    """
    N = a.shape[0]
    
    u = a.copy()    #   u is a copy of given matrix
    L = np.eye(N)   #   L is an eye matrix
    permutation_matrix = np.eye(N)  #   Initialization for permutation matrix
    for j in range(N-1):
        max_index = np.abs(a[j, j:]).argmax() + j # Here
        temporary_matrix = np.eye(N)
        temporary_matrix[j, j] = 0
        temporary_matrix[max_index, max_index] = 0
        temporary_matrix[j, max_index] = 1
        temporary_matrix[max_index, j] = 1
        permutation_matrix = np.dot(permutation_matrix, temporary_matrix) # Mb different?
        u[:,[j, max_index]] = u[:, [max_index, j]]  #   Swap finished
        lam = np.eye(N) #   lam is the same as N
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u
        print('Iteration number {}: \n'.format(j))
        print(u)

        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u, permutation_matrix

In [12]:
#   Test polygon

array = np.random.randint(0, 10, (4, 4))
array_true = array.copy()
permutation_matrix = np.eye(4)
print(array)
for j in range(4):
    max_index = np.abs(array[j, j:]).argmax() + j
    temporary_matrix = np.eye(4)
    temporary_matrix[j, j] = 0
    temporary_matrix[max_index, max_index] = 0
    temporary_matrix[j, max_index] = 1
    temporary_matrix[max_index, j] = 1
    permutation_matrix = np.dot(permutation_matrix, temporary_matrix)
    array[:,[j, max_index]] = array[:, [max_index, j]]
print(array)
print(permutation_matrix)
print(np.dot(array, permutation_matrix))
#print(assert(arr))

[[7 3 1 1]
 [3 4 8 9]
 [0 4 5 0]
 [9 5 5 9]]
[[7 1 1 3]
 [3 9 8 4]
 [0 0 5 4]
 [9 9 5 5]]
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
[[7. 3. 1. 1.]
 [3. 4. 8. 9.]
 [0. 4. 5. 0.]
 [9. 5. 5. 9.]]
