# Simple iteration for systems of linear equations

First, generate a random diagonally dominant matrix, for testing.

In [272]:
import numpy as np
rndm = np.random.RandomState(1234)

n = 10
A = rndm.uniform(size=(n, n)) + np.diagflat([15]*n)
b = rndm.uniform(size=n)

# I.  Jacobi iteration

Given

$$
A x = b
$$

separate the diagonal part $D$,

$$ A = D + (A - D) $$

and write

$$
x = D^{-1} (D - A) x + D^{-1} b\;.
$$

Then iterate

$$
x_{n + 1} = B x_{n} + c\;,
$$

where 

$$
B = D^{-1} (A - D) \qquad \text{and} \qquad c = D^{-1} b
$$


Let's construct the matrix and the r.h.s. for the Jacobi iteration

In [273]:
diag_1d = np.diag(A)

B = -A.copy()
np.fill_diagonal(B, 0)

D = np.diag(diag_1d)
invD = np.diag(1./diag_1d)
BB = invD @ B 
c = invD @ b

In [274]:
# sanity checks
from numpy.testing import assert_allclose

assert_allclose(-B + D, A)


# xx is a "ground truth" solution, compute it using a direct method
xx = np.linalg.solve(A, b)

np.testing.assert_allclose(A@xx, b)
np.testing.assert_allclose(D@xx, B@xx + b)
np.testing.assert_allclose(xx, BB@xx + c)

Check that $\| B\| \leqslant 1$:

In [275]:
np.linalg.norm(BB)

0.36436161983015336

### Do the Jacobi iteration

In [276]:
n_iter = 50

x0 = np.ones(n)
x = x0
for _ in range(n_iter):
    x = BB @ x + c

In [277]:
# Check the result:

A @ x - b

array([ 0.,  0.,  0., -0.,  0.,  0., -0.,  0.,  0.,  0.])

### Task I.1

Collect the proof-of-concept above into a single function implementing the Jacobi iteration. This function should receive the r.h.s. matrix $A$, the l.h.s. vector `b`, and the number of iterations to perform.


The matrix $A$ in the illustration above is strongly diagonally dominant, by construction. 
What happens if the diagonal matrix elements of $A$ are made smaller? Check the convergence of the Jacobi iteration, and check the value of the norm of $B$.

(20% of the total grade)


In [278]:
def jacob(A, b, rtol=1e-16, niter = 500):
    dgA = np.diag(np.diag(A))
    B = A - dgA
    x = np.ones(b.shape[0])
    dgA_ = np.diag(1/np.diag(dgA))
    n = 0
    for i in range(niter):
        normB = np.linalg.norm(dgA_ @ -B)
        if normB > 1: #checking convergence
            print("don't converge")
            break
        x_s = (dgA_ @ -B ) @ x + dgA_ @ b
        n +=1
        if np.linalg.norm(x_s - x) <= rtol: #elimination of excess iterations
            break
        else:
            x = x_s
    return x, n


In [279]:
n = 10
np.set_printoptions(suppress=True)
for l in range(1,20): #we check some dominance of matrix
    A = rndm.uniform(size=(n, n)) + np.diagflat([l]*n)
    b = rndm.uniform(size=n)
    xx = np.linalg.solve(A,b)
    x, m = jacob(A,b)
    print(np.abs(xx-x),'Diag multiply: ',l, 'Niter: ', m)

don't converge
[1.69028049 0.34674145 1.25212443 0.94810969 0.63289142 1.68956675
 0.76193901 0.92340856 1.04634973 0.04209147] Diag multiply:  1 Niter:  0
don't converge
[0.84394861 0.88037364 0.66600454 0.80867916 0.7869155  1.14538078
 0.73429736 1.22672463 1.12557723 0.99134399] Diag multiply:  2 Niter:  0
don't converge
[0.88492617 1.11121635 0.78623234 1.16486714 0.86765002 1.08494476
 1.04304059 0.83135432 0.76590397 0.91315443] Diag multiply:  3 Niter:  0
don't converge
[1.03429143 1.00009777 0.94169352 0.96024901 1.03918878 1.02263367
 0.92457748 1.01385928 0.83446026 0.85449813] Diag multiply:  4 Niter:  0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Diag multiply:  5 Niter:  169
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Diag multiply:  6 Niter:  113
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Diag multiply:  7 Niter:  71
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Diag multiply:  8 Niter:  66
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Diag multiply:  9 Niter:  52
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Diag multiply:  10 Niter:  40
[0. 0. 

# II. Seidel's iteration.

##### Task II.1

Implement the Seidel's iteration. 

Test it on a random matrix. Study the convergence of iterations, relate to the norm of the iteration matrix.

(30% of the total grade)

In [280]:
def seidel(A, b, rtol = 1e-16, niter= 500):
    U = np.triu(A,k=1)
    L = np.tril(A,k=0)
    L_ = np.linalg.inv(L)
    x = np.ones(b.shape[0])
    n = 0
    for i in range(niter):
        normB = np.linalg.norm(L_ @ U)
        if normB > 1: #checking convergence
            print("don't converge")
            break
        x_s = L_ @ b - L_@ U @ x
        n += 1 
        if np.linalg.norm(x_s - x)<= rtol:
            break
        x = x_s
    return x,n

In [281]:
#convergence is only guaranteed if the matrix is either diagonally dominant, or symmetric and positive definite
for i in range(10):
    n = 10
    A = rndm.uniform(size=(n, n)) + np.diagflat([5]*n)#diagonally dominant
    b = rndm.uniform(size=n)
    xx = np.linalg.solve(A,b)
    x, k = seidel(A,b)
    print('DDominant: ',np.abs(xx-x),'Niter: ', k)

    a = np.random.rand(n, n)
    M = np.tril(a,-1) + np.tril(a, -1).T + np.diagflat([5]*n)#symmetric and positive definite
    xx1 = np.linalg.solve(M,b)
    x1,p = seidel(M,b)
    print('PSymmetric: ',np.abs(xx1-x1), 'Niter: ', p)

    C = rndm.uniform(size=(n, n)) #random won't converge
    xx2 = np.linalg.solve(C,b)
    x2,u = seidel(C,b)

    print('Random: ', np.abs(xx2-x2), 'Niter: ', u)


DDominant:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  28
PSymmetric:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  23
don't converge
Random:  [0.81075754 2.52057467 2.0665217  0.78188964 1.81430634 0.4546695
 1.42871118 0.04475773 2.83897545 0.5963693 ] Niter:  0
DDominant:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  22
PSymmetric:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  27
don't converge
Random:  [0.98465121 2.2042164  0.09611676 0.59245988 1.57833379 1.28030354
 1.76481199 1.4340043  2.9885939  1.00000378] Niter:  0
DDominant:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  25
PSymmetric:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  27
don't converge
Random:  [5.67939014 3.90833017 1.09557964 4.28201803 0.40121489 5.42195606
 1.23847474 0.00939071 0.08293836 0.39229512] Niter:  0
DDominant:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  22
PSymmetric:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  23
don't converge
Random:  [  1.5090538   44.75717273  31.6173864  120.67020884  33.32795666
  57.29384097   6.96836204

# III. Minimum residual scheme

### Task III.1

Implement the $\textit{minimum residual}$ scheme: an explicit non-stationary method, where at each step you select the iteration parameter $\tau_n$ to minimize the residual $\mathbf{r}_{n+1}$ given $\mathbf{r}_n$. Test it on a random matrix, study the convergence to the solution, in terms of the norm of the residual and the deviation from the ground truth solution (which you can obtain using a direct method). Study how the iteration parameter $\tau_n$ changes as iterations progress.

(50% of the grade)

In [282]:
def min_res(A, b, x0, rtol=1e-16, niter = 5000):
    x = x0
    n = 0
    r_ = np.array([])
    tau_ = np.array([])
    for i in range(niter):
        r = A @ x - b
        r_ = np.append(r_, np.linalg.norm(r))
        tau = np.dot(r, A @ r)/np.linalg.norm(A @ r)**2 #this I took from lecture
        tau_ = np.append(tau_, tau)
        x_s = x - tau * r
        n += 1
        if np.linalg.norm(x_s - x)<= rtol:
            break
        x = x_s
    return x, n, r_[0], r_[n-1], tau_

In [283]:
for i in range(10):
    n = 10
    A = rndm.uniform(size=(n, n)) + np.diagflat([5]*n)#diagonally dominant
    b = rndm.uniform(size=n)
    x0 = np.ones(b.shape[0])
    xx = np.linalg.solve(A,b)
    x,k, r11, r12 ,tau1 = min_res(A, b, x0)
    print('DDominant: ',np.abs(xx-x), 'Niter: ', k, 'Starts / Ends:',r11/r12)

    a = np.random.rand(n, n)
    M = np.tril(a,-1) + np.tril(a, -1).T + np.diagflat([2]*n)#symmetric and positive definite
    xx1 = np.linalg.solve(M,b)
    x1, p, r21, r22, tau2 = min_res(M, b, x0)
    print('pSymmetric: ',np.abs(xx1-x1), 'Niter: ', p, 'Starts / Ends:',r21/r22)

    C = rndm.uniform(size=(n, n)) #random won't converge
    xx2 = np.linalg.solve(C,b)
    x2, u, r31, r32, tau3 = min_res(C,b, x0)
    print('Random: ', np.abs(xx2-x2), ', Niter: ', u)

DDominant:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  38 Starts / Ends: 5.239957853579172e+16
pSymmetric:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  407 Starts / Ends: 3.3375497647887492e+16
Random:  [2.16955783 0.27641392 0.899283   0.88010188 0.95792678 0.84879165
 2.05348242 1.11348924 1.26976784 1.57724567] , Niter:  28
DDominant:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  34 Starts / Ends: 6.974753698234969e+16
pSymmetric:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  870 Starts / Ends: 2.7939622638932908e+16
Random:  [1.25200353 2.17047675 1.14758405 0.55060204 0.5853526  1.74236083
 2.9316221  2.50334497 0.83888076 0.16045034] , Niter:  36
DDominant:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Niter:  38 Starts / Ends: 4.595153145704665e+16
pSymmetric:  [9.24937796 8.16449193 4.50848894 1.67292084 4.37316204 6.78585821
 4.18286647 1.69301869 5.37537667 7.14151012] Niter:  5000 Starts / Ends: 28.176469639745235
Random:  [ 1.95689268  9.64300872  8.44755544 25.51715211  3.51106796  6.68578685
  3.37695

In [288]:
#Now check changing of tau
n = 10
A = rndm.uniform(size=(n, n)) + np.diagflat([5]*n)#diagonally dominant
b = rndm.uniform(size=n)
x0 = np.ones(b.shape[0])
xx = np.linalg.solve(A,b)
x,k, r11, r12 ,tau1 = min_res(A, b, x0)
print('DDominant: ',tau1)

a = np.random.rand(n, n)
M = np.tril(a,-1) + np.tril(a, -1).T + np.diagflat([2]*n)#symmetric and positive definite
xx1 = np.linalg.solve(M,b)
x1, p, r21, r22, tau2 = min_res(M, b, x0)
print('pSymmetric: ',tau2)


C = rndm.uniform(size=(n, n)) #random won't converge
xx2 = np.linalg.solve(C,b)
x2, u, r31, r32, tau3 = min_res(C,b, x0)
print('Random: ', tau3)
# I can see oscillations between tau(n) and tau(n+1)

DDominant:  [0.10021221 0.19770213 0.12994483 0.14556109 0.13958483 0.14417148
 0.14528196 0.13932249 0.14939774 0.13512173 0.15283814 0.13190624
 0.15562344 0.12947468 0.1576949  0.12766819 0.15900707 0.12640468
 0.15950069 0.12566233 0.15908334 0.12547509 0.15762331 0.12594844
 0.15495772 0.12730645 0.15094532 0.12999838 0.14566198 0.1348972
 0.13987657 0.14320113 0.13518349 0.15414038 0.13171023 0.1632178
 0.12977059 0.16947929 0.12077294]
pSymmetric:  [0.15222089 0.61760824 0.60096177 0.31935747 0.24969548 0.3343445
 0.25066606 0.33472536 0.25078138 0.33487049 0.2508442  0.33496242
 0.25088903 0.3350356  0.25092828 0.33510483 0.25096765 0.33517724
 0.25101001 0.33525661 0.25105698 0.33534526 0.25110963 0.33544477
 0.25116873 0.33555641 0.25123492 0.33568123 0.25130875 0.33582009
 0.25139061 0.33597362 0.25148081 0.33614224 0.25157948 0.336326
 0.25168655 0.33652462 0.25180173 0.33673736 0.25192447 0.33696303
 0.25205396 0.33719996 0.25218915 0.33744603 0.25232871 0.33769872
 0.2524