# I. $LU$ factorization of a square matrix

Consider a simple naive implementation of the LU decomposition. 

Note that we're using the `numpy` arrays to represent matrices [do **not** use `np.matrix`].

In [68]:
import numpy as np

def diy_lu(a):
    """Construct the LU decomposition of the input matrix.
    
    Naive LU decomposition: work column by column, accumulate elementary triangular matrices.
    No pivoting.
    """
    N = a.shape[0]
    
    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u

        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u

In [69]:
# Now, generate a full rank matrix and test the naive implementation

import numpy as np

N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)
print(a)

np.linalg.matrix_rank(a)

[[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]]


6

In [70]:
# Tweak the printing of floating-point numbers, for clarity
np.set_printoptions(precision=3)

In [71]:
L, u = diy_lu(a)

print(L, "\n")
print(u, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print(L@u - a)

[[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    1.455 1.    0.    0.    0.   ]
 [1.    1.714 1.742 1.    0.    0.   ]
 [1.    1.882 2.276 2.039 1.    0.   ]
 [1.    2.    2.671 2.944 2.354 1.   ]] 

[[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -1.125e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.625e-01  4.574e-01  5.975e-01  7.013e-01]
 [ 0.000e+00  1.110e-16  0.000e+00 -2.197e-02 -4.480e-02 -6.469e-02]
 [ 0.000e+00 -2.819e-16  0.000e+00  0.000e+00  8.080e-04  1.902e-03]
 [ 0.000e+00  3.369e-16  0.000e+00 -1.541e-18  2.168e-19 -1.585e-05]] 

[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  2.220e-16 -1.110e-16 -1.665e-16]
 [ 0.000e+00  0.000e+00  2.220e-16 -5.551e-17 -1.665e-16 -1.665e-16]
 [ 0.000e+00  0.000e+00 -1.110e-16  2.776e-16 -2.776e-16  5.551e-17]
 

# II. The need for pivoting

Let's tweak the matrix a little bit, we only change a single element:

In [72]:
a1 = a.copy()
a1[1, 1] = 3
print(a1)

[[3.    3.    3.    3.    3.    3.   ]
 [3.    3.    1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]]


Resulting matix still has full rank, but the naive LU routine breaks down.

In [73]:
np.linalg.matrix_rank(a1)

6

In [74]:
l, u = diy_lu(a1)

print(l, u)

[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]] [[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]


### Test II.1

For a naive LU decomposition to work, all leading minors of a matrix should be non-zero. Check if this requirement is satisfied for the two matrices `a` and `a1`.

(20% of the grade)

In [75]:
def minor_check(b):
    n = b.shape[0]
    for i in range(n, 1, -1):
        det = np.linalg.det(b)
        if det ==  0:
            k = False
            break
        else : 
            k = True
        b = b[:(i-1),:(i-1)]
    return k
l = minor_check(a), minor_check(a1)
print(l)


(True, False)


### Test II.2

Modify the `diy_lu` routine to implement column pivoting. Keep track of pivots, you can either construct a permutation matrix, or a swap array (your choice).

(40% of the grade)

Implement a function to reconstruct the original matrix from a decompositon. Test your routines on the matrices `a` and `a1`.

(40% of the grade)

In [76]:
def diy_lu_mod(a):
    N = a.shape[0]
    P = np.zeros(a.shape)

    u = a.copy()
    L = np.eye(N)
    det = np.linalg.det(a)
    if det == 0:
        return False
    else:
        for j in range(N-1):
            dj = np.linalg.det(u[:j+2,:j+2])
            while dj == 0:
                i = j+1
                while i < N-1:
                    u[:,[i,i+1]] = u[:,[i+1,i]]
                    i +=1
                dj = np.linalg.det(u[:j+2,:j+2])
            lam = np.eye(N)
            gamma = u[j+1:, j] / u[j, j]
            lam[j+1:, j] = -gamma
            u = lam @ u

            lam[j+1:, j] = gamma
            L = L @ lam
    P = np.linalg.solve(L@u, a)
    return L, u, P


L, u, P = diy_lu_mod(a)
print(L, "\n")
print(u, "\n")
print(P, "\n")

L1, u1, P1 = diy_lu_mod(a1)
print(L1, "\n")
print(u1, "\n")
print(P1, "\n")

[[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    1.455 1.    0.    0.    0.   ]
 [1.    1.714 1.742 1.    0.    0.   ]
 [1.    1.882 2.276 2.039 1.    0.   ]
 [1.    2.    2.671 2.944 2.354 1.   ]] 

[[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -1.125e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.625e-01  4.574e-01  5.975e-01  7.013e-01]
 [ 0.000e+00  1.110e-16  0.000e+00 -2.197e-02 -4.480e-02 -6.469e-02]
 [ 0.000e+00 -2.819e-16  0.000e+00  0.000e+00  8.080e-04  1.902e-03]
 [ 0.000e+00  3.369e-16  0.000e+00 -1.541e-18  2.168e-19 -1.585e-05]] 

[[ 1.000e+00 -2.294e-15 -1.163e-16  1.190e-14 -1.950e-14 -3.022e-16]
 [-0.000e+00  1.000e+00  2.115e-15 -2.275e-12  4.078e-12  6.465e-14]
 [-0.000e+00 -9.134e-12  1.000e+00  2.774e-11 -5.061e-11 -7.918e-13]
 [ 0.000e+00  3.201e-11  8.436e-14  1.000e+00  1.745e-10  2.706e-12]
 [-0.000e+00 -4.136e-11 -1.076e-13  1.210e-10  1.000e+00 -3.446e-12]
 

In [77]:
def going_back(L,u,p):
    return L @ u @ p

In [78]:
a_ = going_back(L,u,P) # We didn't make permutation for this matrix
print(a_, "\n", a - a_)

[[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]] 
 [[ 0.000e+00 -4.441e-16  0.000e+00 -4.441e-16  8.882e-16  0.000e+00]
 [ 0.000e+00 -6.661e-16  2.220e-16  0.000e+00  2.220e-16  1.110e-16]
 [ 0.000e+00 -6.661e-16  2.220e-16  0.000e+00  2.220e-16  2.220e-16]
 [ 0.000e+00 -4.441e-16  0.000e+00  1.665e-16  6.661e-16  1.665e-16]
 [ 0.000e+00 -7.772e-16  3.331e-16  5.551e-17  1.665e-16 -5.551e-17]
 [ 0.000e+00 -7.772e-16  3.886e-16  1.110e-16  2.776e-16  0.000e+00]]


In [79]:
a1_ = going_back(L1, u1, P1)
print(a1_, "\n", a1 - a1_)

[[3.    3.    3.    3.    3.    3.   ]
 [3.    3.    1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]] 
 [[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00 -4.441e-16  0.000e+00]
 [ 0.000e+00  0.000e+00 -4.441e-16 -4.441e-16 -1.110e-16 -3.331e-16]
 [ 0.000e+00 -2.220e-16 -4.441e-16 -7.772e-16  1.110e-16 -4.996e-16]
 [ 0.000e+00  0.000e+00 -6.661e-16 -4.996e-16  1.665e-16  5.551e-17]
 [ 0.000e+00  1.110e-16 -4.441e-16 -4.441e-16 -1.110e-16 -3.053e-16]
 [ 0.000e+00  0.000e+00 -3.331e-16 -4.441e-16 -2.776e-17 -2.498e-16]]
